### ISSUE TITLE
MinusFace代码运行报错

### ISSUE THREAD

**Issue by xuanxie2000** [Tencent/TFace#138]
命令行：bash local_train.sh

Original Traceback (most recent call last):
  File "/root/miniconda3/envs/MinusFace/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/envs/MinusFace/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/MinusFace/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/autodl-tmp/TFace-master/recognition/tasks/minusface/../../torchkit/data/dataset.py", line 164, in __getitem__
    image, label = self.sample_parser(*sample)
TypeError: __call__() takes 3 positional arguments but 4 were given

为什么会出错呢？请教各位大佬

**Comment by aigy0828** [comment]
我也有这个问题，请问解决了吗？
