### ISSUE TITLE
RESUME got error on distfc

### ISSUE THREAD

**Issue by John1231983** [Tencent/TFace#32]
Hi author, I resume the training from epoch 21 with the setting.
```
  GNU nano 4.8                                                                    tasks/distfc/train_config.yaml                                                                               
SEED: 1337 # random seed for reproduce results
DATA_ROOT: '/home/john123/TFace/' # the parent root where your train/val/test data are stored
INDEX_ROOT: '/home/john123/TFace/'
DATASETS:  # the dataset index name
    - name: TFR-MS1M-list
      batch_size: 96
      weight: 1.

BACKBONE_RESUME: "/home/john123/ckpt/Backbone_Epoch_22_checkpoint.pth"
HEAD_RESUME: "/home/john123/ckpt/HEAD_Epoch_22"
META_RESUME: "/home/john123/ckpt/Optimizer_Epoch_22_checkpoint.pth"

# BACKBONE_NAME: 'EfficientNetB0'
BACKBONE_NAME: 'IR_34'
DIST_FC: true
TFRRECORD: true
MODEL_ROOT: './ckpt/' # the root to buffer your checkpoints
LOG_ROOT: './tensorboard' # the root to log your train/val status
HEAD_NAME: "CurricularFace" # support:  ['ArcFace', 'CurricularFace', 'CosFace']
LOSS_NAME: 'DistCrossEntropy' # support: ['DistCrossEntropy', 'Softmax']
INPUT_SIZE: [112, 112] # support: [112, 112] and [224, 224]
RGB_MEAN: [0.5, 0.5, 0.5] # for normalize inputs to [-1, 1]
RGB_STD: [0.5, 0.5, 0.5]
INPUT_SIZE: [112, 112]
EMBEDDING_SIZE: 512 # feature dimension
LR: 0.1 # initial LR
START_EPOCH: 0 # start epoch
WARMUP_STEP: -1
NUM_EPOCH: 26 # total epoch number
WEIGHT_DECAY: 0.0005 # do not apply to batch_norm parameters
MOMENTUM: 0.9
STAGES: [10, 18, 24] # epoch stages to decay learning rate
WORLD_SIZE: 1
RANK: 0
LOCAL_RANK: 0
DIST_BACKEND: 'nccl'
DIST_URL: 'env://'
NUM_WORKERS: 8
AMP: true # fp16 for backbone

```
However, I got the error. Could you help me to fix it?
```
Traceback (most recent call last):
  File "./tasks/distfc/train_distfc.py", line 150, in <module>
    main()
  File "./tasks/distfc/train_distfc.py", line 146, in main
    task.train()
  File "./tasks/distfc/train_distfc.py", line 138, in train
    self._loop_step(train_loaders, backbone, heads, loss, opt, scaler, epoch, class_splits)
  File "./tasks/distfc/train_distfc.py", line 88, in _loop_step
    scaler.step(opt)
  File "/home/john123/pytorch/lib/python3.7/site-packages/torch/cuda/amp/grad_scaler.py", line 338, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/home/john123/pytorch/lib/python3.7/site-packages/torch/cuda/amp/grad_scaler.py", line 285, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/home/john123/pytorch/lib/python3.7/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/home/john123/pytorch/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/john123/pytorch/lib/python3.7/site-packages/torch/optim/sgd.py", line 117, in step
    nesterov=nesterov)
  File "/home/john123/pytorch/lib/python3.7/site-packages/torch/optim/_functional.py", line 173, in sgd
    buf.mul_(momentum).add_(d_p, alpha=1 - dampening)
RuntimeError: The size of tensor a (257489) must match the size of tensor b (257488) at non-singleton dimension 1

```

**Comment by wjxzju** [comment]
是不是生成的训练数据list有问题

**Comment by wjxzju** [comment]
看起来是AMP的错误，我们这边看下能否复现
