### ISSUE TITLE
how resolve this problem?env://

### ISSUE THREAD

**Issue by xingjunhong** [Tencent/TFace#68]
SEED: 1337 # random seed for reproduce results
DATA_ROOT: '/youtu-face/ata_root/remote_tfrecord' # the parent root where your train/val/test data are stored
INDEX_ROOT: '/youtu-face/train_data/'
DATASETS:  # the dataset index name
    - name: TFR-deepglint_360k_new
      batch_size: 128
      weight: 1.0
      scale: 64
      margin: 0.4
  
BACKBONE_RESUME: ""
HEAD_RESUME: ""
META_RESUME: ""

# BACKBONE_NAME: 'EfficientNetB0'
INPUT_SIZE: [112, 112] # support: [112, 112] and [224, 224]
BACKBONE_NAME: 'IR_50'
EMBEDDING_SIZE: 512 # feature dimension

MODEL_ROOT: './ckpt/' # the root to buffer your checkpoints
LOG_ROOT: './tensorboard' # the root to log your train/val status

DIST_FC: true
HEAD_NAME: "PartialFC" # support:  ['ArcFace', 'CurricularFace', 'CosFace']
LOSS_NAME: 'DistCrossEntropy' # support: ['DistCrossEntropy', 'Softmax']

RGB_MEAN: [0.5, 0.5, 0.5] # for normalize inputs to [-1, 1]
RGB_STD: [0.5, 0.5, 0.5]

LRS: [0.1, 0.01, 0.001, 0.0001, 0.00001] # initial LR
WARMUP_STEP: -1
STAGES: [8, 12, 15, 18] # epoch stages to decay learning rate

START_EPOCH: 0 # start epoch
NUM_EPOCH: 20 # total epoch number
SAVE_EPOCHS: [1, 15, 18, 20]

WEIGHT_DECAY: 0.0005 # do not apply to batch_norm parameters
MOMENTUM: 0.9

WORLD_SIZE: 1
RANK: 0
LOCAL_RANK: 0
DIST_BACKEND: 'nccl'
DIST_URL: 'env://'

NUM_WORKERS: 8

AMP: true # fp16 for backbone

Traceback (most recent call last):
  File "/work/05.TFace/TFace-master/recognition/train.py", line 180, in <module>
    main()
  File "/work/05.TFace/TFace-master/recognition/train.py", line 175, in main
    task.init_env()
  File "/work/05.TFace/TFace-master/recognition/torchkit/task/base_task.py", line 98, in init_env
    init_method=self.cfg["DIST_URL"])
  File "/my_app/anaconda3/envs/05.TFace-pytorch1.6-python3.6/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 422, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/my_app/anaconda3/envs/05.TFace-pytorch1.6-python3.6/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 148, in _env_rendezvous_handler
    raise _env_error("RANK")
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set

**Comment by wjxzju** [comment]
你的启动脚本是怎么样的？

**Comment by xingjunhong** [comment]
train.py,这个我是直接运行的

**Comment by wjxzju** [comment]
看一下local_train.sh的启动脚本，需要用 torch.distributed.launch这个模块启动

**Comment by xingjunhong** [comment]
> 看一下local_train.sh的启动脚本，需要用 torch.distributed.launch这个模块启动

我运行该脚本后发现这样一个错误，如何解决？
2022-07-27 06:36:26,661: Dataset TFR-deepglint_360k_new, batch_size 128, weight 1.000000, scale 64, margin 0.400000
Traceback (most recent call last):
  File "train.py", line 180, in <module>
    main()
  File "train.py", line 175, in main
    task.init_env()
  File "/work/05.TFace/TFace-master/recognition/torchkit/task/base_task.py", line 100, in init_env
    rank=0,
  File "/my_app/anaconda3/envs/05.TFace-pytorch1.6-python3.6/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 422, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/my_app/anaconda3/envs/05.TFace-pytorch1.6-python3.6/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 172, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
RuntimeError: Address already in use
Traceback (most recent call last):
  File "/my_app/anaconda3/envs/05.TFace-pytorch1.6-python3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/my_app/anaconda3/envs/05.TFace-pytorch1.6-python3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/my_app/anaconda3/envs/05.TFace-pytorch1.6-python3.6/lib/python3.6/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/my_app/anaconda3/envs/05.TFace-pytorch1.6-python3.6/lib/python3.6/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/my_app/anaconda3/envs/05.TFace-pytorch1.6-python3.6/bin/python', '-u', 'train.py', '--local_rank=7', '--port', '12345']' returned non-zero exit status 1.

**Comment by Kellybaibai** [comment]
这个问题是因为端口被占用了，可以看一下`lsof -i -P -n`，看看有哪些进程，然后把它们kill掉
