### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by Adesoji1** [Tencent/TFace#75]
![image](https://user-images.githubusercontent.com/20457308/188138570-35374801-6330-43cb-b24a-3966215ad967.png)

**sh ./train.sh -1 "/home/adesoji/tfaceenv/TFace-master/security/tasks/Face-Anti-Spoofing/DCN/configs" 5000**

Running this command below resulted intoAssertion Error, how do i correct this?
/home/adesoji/tfaceenv/lib/python3.10/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/adesoji/tfaceenv/lib/python3.10/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/adesoji/tfaceenv/lib/python3.10/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/adesoji/tfaceenv/lib/python3.10/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/adesoji/tfaceenv/lib/python3.10/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/adesoji/tfaceenv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/adesoji/tfaceenv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 214, in launch_agent
    spec = WorkerSpec(
  File "<string>", line 15, in __init__
  File "/home/adesoji/tfaceenv/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 87, in __post_init__
    assert self.local_world_size > 0
AssertionError

**Comment by Adesoji1** [comment]
I Resolved this issue by installing PyTorch version 1.8 instead of using version 1.12

**Comment by stonejane** [comment]
@Adesoji1 Hi, I have problems with reproducing this project, and I wonder whether did you get the result as good as shown in the paper of DCN. If so, may I ask for the hyperparameters(lr, bs, and so on) that you used? It would really help me out if you could kindly give me a reply😭🥺
